// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9ZWe_dcdF1tl_ZezM1gJXZ38qMR0I1w',
    appId: '1:626250741141:web:08a90466359ed7b39e729c',
    messagingSenderId: '626250741141',
    projectId: 'izmir-fb3fb',
    authDomain: 'izmir-fb3fb.firebaseapp.com',
    storageBucket: 'izmir-fb3fb.appspot.com',
    measurementId: 'G-YT2LJ7H3YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHR-T2SApHF_MzxNFrNIzdXwwCF0gcRk',
    appId: '1:626250741141:android:1560dd2c54485fee9e729c',
    messagingSenderId: '626250741141',
    projectId: 'izmir-fb3fb',
    storageBucket: 'izmir-fb3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkcdr116s9SqeO7BHbbJxIC8YO8LHFLM',
    appId: '1:626250741141:ios:b9b911c87b9701b19e729c',
    messagingSenderId: '626250741141',
    projectId: 'izmir-fb3fb',
    storageBucket: 'izmir-fb3fb.appspot.com',
    iosClientId: '626250741141-bffiq4k2ml4vluflennb5ul2b4ig388j.apps.googleusercontent.com',
    iosBundleId: 'com.example.izmir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkcdr116s9SqeO7BHbbJxIC8YO8LHFLM',
    appId: '1:626250741141:ios:b9b911c87b9701b19e729c',
    messagingSenderId: '626250741141',
    projectId: 'izmir-fb3fb',
    storageBucket: 'izmir-fb3fb.appspot.com',
    iosClientId: '626250741141-bffiq4k2ml4vluflennb5ul2b4ig388j.apps.googleusercontent.com',
    iosBundleId: 'com.example.izmir',
  );
}
